"""cria configuracao empresa

Revision ID: 175610940780
Revises: ae7bcfe47e88
Create Date: 2026-09-01 10:41:08.450178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175610940780'
down_revision = 'ae7bcfe47e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=True),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=True),
    sa.Column('cnpj', sa.String(length=30), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=50), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('responsavel', sa.String(length=150), nullable=True),
    sa.Column('chave_pix', sa.String(length=150), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('agencia', sa.String(length=30), nullable=True),
    sa.Column('conta', sa.String(length=50), nullable=True),
    sa.Column('site', sa.String(length=200), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracao_empresa')
    # ### end Alembic commands ###
