"""cria tabela de produtos

Revision ID: 755be75050a3
Revises: 
Create Date: 2026-08-24 08:21:53.293289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755be75050a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('preco_normal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_atacado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gera_comissao', sa.Boolean(), nullable=False),
    sa.Column('percentual_comissao', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    # ### end Alembic commands ###
