"""cria retiradas de comissao

Revision ID: e21083137712
Revises: ef5214cc5fb0
Create Date: 2026-08-25 09:05:11.199522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21083137712'
down_revision = 'ef5214cc5fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retiradas_comissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piscineiro_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_retirada', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['piscineiro_id'], ['piscineiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retiradas_comissao')
    # ### end Alembic commands ###
