"""cria estrutura de notinhas pagamentos e anexos

Revision ID: ef5214cc5fb0
Revises: b20df0ad40e9
Create Date: 2026-08-24 16:24:27.445660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5214cc5fb0'
down_revision = 'b20df0ad40e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notinhas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('piscineiro_id', sa.Integer(), nullable=True),
    sa.Column('data_retirada', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsavel_cobranca', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['piscineiro_id'], ['piscineiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_notinha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notinha_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('nome_produto', sa.String(length=150), nullable=False),
    sa.Column('marca_produto', sa.String(length=100), nullable=True),
    sa.Column('gera_comissao', sa.Boolean(), nullable=False),
    sa.Column('percentual_comissao', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valor_comissao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['notinha_id'], ['notinhas.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observacoes_notinha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notinha_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notinha_id'], ['notinhas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notinha_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('pago_por', sa.String(length=20), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notinha_id'], ['notinhas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anexos_notinha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notinha_id', sa.Integer(), nullable=False),
    sa.Column('pagamento_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notinha_id'], ['notinhas.id'], ),
    sa.ForeignKeyConstraint(['pagamento_id'], ['pagamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anexos_notinha')
    op.drop_table('pagamentos')
    op.drop_table('observacoes_notinha')
    op.drop_table('itens_notinha')
    op.drop_table('notinhas')
    # ### end Alembic commands ###
